services:
  nginx:
    container_name: lab-02-nginx
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/share/nginx/html/lab-02
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro