server {
  listen 8080;

  location /lab-02/ {
    alias /usr/share/nginx/html/lab-02/;

    location ~ ^/lab-02/ejercicio-0([123])\.html$ {
        alias /usr/share/nginx/html/lab-02/ejercicio-0$1/ejercicio-0$1.html;
    }
  }
}